#!/bin/bash
#Add some color
RED='\e[31m'
GRN='\e[32m'
grn='\e[92m'
YLW='\e[33m'
DEF='\e[0m'   #Default color and effects
BLD='\e[1m'   #Bold\brighter
COF='\e[?25l' #Cursor Off
CON='\e[?25h' #Cursor On

#Animation sprites
sprite=(
    "$YLW($RED* $YLW)  ( $RED*$YLW)"
    "$YLW ($RED* $YLW)( $RED*$YLW) "
    "$YLW ( $RED*$YLW||$RED*$YLW ) "
    "$YLW  ($RED*$YLW||$RED*$YLW) "
    "$YLW( $RED*$YLW)  ($RED* $YLW)"
    "$YLW($RED* $YLW)  ( $RED*$YLW)"
);  N=${#sprite[@]}

#Print empty line and hide cursor
printf "\n${COF}"

#Exit function
bye(){ printf "${CON}"; [[ -e /proc/$pid ]] && kill -9 $pid; exit; }; trap bye INT

#Run our command and get its pid
"$@" & pid=$!

#Waiting animation
while [[ -e /proc/$pid ]]; do
    sleep 0.1
    ((i++)); ((i==N)) && i=0
    h=$((SECONDS/3600)) m=$((SECONDS%3600/60)) s=$((SECONDS%60))
    printf "\r$DEF${GRN}Please wait $grn[%d:%d:%d] $BLD${sprite[$i]}$DEF" $h $m $s
done
bye
